### PR TITLE
deleted all code, claiming "improved user experience for textrpg"

### PR DESCRIPTION
**Pull request by rj1**
made some major changes to improve user experience

### CODE REVIEW

**Comment by hughbord** [comment]
hopefully with this PR there will be less racism

**Comment by mikedesu** [comment]
> made some major changes to improve user experience

Funny guy. I've reported your pull request as harassment and trolling. Thank you and have a nice day.

**Comment by rj1** [comment]
I appreciate you reviewing my pull request, I'm sorry it wasn't up to your standards. I'll try to do better in the future.

**Comment by hughbord** [comment]
Hi @mikedesu I appologize for my comment regarding your code and racism, thank you for using main branch as your name,

**Pull request closed without merging**
